version: '3'
services:
  db:
    container_name: cat-search-db
    image: mysql:8.0.32
    environment:
      MYSQL_DATABASE: app
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    restart: always
