insert into app.cat (cat_id, url, width, height, breed_id, breed_name, temperament, origin)
values  ('xnzzM6MBI', 'https://cdn2.thecatapi.com/images/xnzzM6MBI.jpg', 2592, 1629, 'abys', 'Abyssinian', 'Active, Energetic, Independent, Intelligent, Gentle', 'Egypt'),
        ('vH0bd0YDH', 'https://cdn2.thecatapi.com/images/vH0bd0YDH.jpg', 1335, 1206, 'abob', 'American Bobtail', 'Intelligent, Interactive, Lively, Playful, Sensitive', 'United States'),
        ('8D--jCd21', 'https://cdn2.thecatapi.com/images/8D--jCd21.jpg', 1280, 936, 'awir', 'American Wirehair', 'Affectionate, Curious, Gentle, Intelligent, Interactive, Lively, Loyal, Playful, Sensible, Social', 'United States'),
        ('zlpgGWqN7', 'https://cdn2.thecatapi.com/images/zlpgGWqN7.jpg', 3840, 2400, 'amau', 'Arabian Mau', 'Affectionate, Agile, Curious, Independent, Playful, Loyal', 'United Arab Emirates'),
        ('mnD88Lsjd', 'https://cdn2.thecatapi.com/images/mnD88Lsjd.jpg', 1920, 1200, 'amau', 'Arabian Mau', 'Affectionate, Agile, Curious, Independent, Playful, Loyal', 'United Arab Emirates'),
        ('zTiuUpmqf', 'https://cdn2.thecatapi.com/images/zTiuUpmqf.jpg', 4553, 3036, 'amis', 'Australian Mist', 'Lively, Social, Fun-loving, Relaxed, Affectionate', 'Australia'),
        ('4ndvXwCiI', 'https://cdn2.thecatapi.com/images/4ndvXwCiI.jpg', 1280, 960, 'bali', 'Balinese', 'Affectionate, Intelligent, Playful', 'United States'),
        ('OaTQfIktG', 'https://cdn2.thecatapi.com/images/OaTQfIktG.jpg', 1600, 1138, 'bali', 'Balinese', 'Affectionate, Intelligent, Playful', 'United States'),
        ('VZ3qFLIe3', 'https://cdn2.thecatapi.com/images/VZ3qFLIe3.jpg', 750, 937, 'beng', 'Bengal', 'Alert, Agile, Energetic, Demanding, Intelligent', 'United States'),
        ('iWyIaja-G', 'https://cdn2.thecatapi.com/images/iWyIaja-G.jpg', 1080, 769, 'beng', 'Bengal', 'Alert, Agile, Energetic, Demanding, Intelligent', 'United States'),
        ('Rl39SPjDO', 'https://cdn2.thecatapi.com/images/Rl39SPjDO.png', 1198, 1379, 'beng', 'Bengal', 'Alert, Agile, Energetic, Demanding, Intelligent', 'United States'),
        ('H_UWbOfra', 'https://cdn2.thecatapi.com/images/H_UWbOfra.jpg', 1200, 1200, 'beng', 'Bengal', 'Alert, Agile, Energetic, Demanding, Intelligent', 'United States'),
        ('HOrX5gwLS', 'https://cdn2.thecatapi.com/images/HOrX5gwLS.jpg', 1376, 814, 'birm', 'Birman', 'Affectionate, Active, Gentle, Social', 'France'),
        ('Kjf-Z_8YE', 'https://cdn2.thecatapi.com/images/Kjf-Z_8YE.jpg', 1600, 1200, 'birm', 'Birman', 'Affectionate, Active, Gentle, Social', 'France'),
        ('aZii7hC77', 'https://cdn2.thecatapi.com/images/aZii7hC77.jpg', 1200, 800, 'bomb', 'Bombay', 'Affectionate, Dependent, Gentle, Intelligent, Playful', 'United States'),
        ('b6Co9acGP', 'https://cdn2.thecatapi.com/images/b6Co9acGP.jpg', 800, 450, 'bsho', 'British Shorthair', 'Affectionate, Easy Going, Gentle, Loyal, Patient, calm', 'United Kingdom'),
        ('nJsljkalm', 'https://cdn2.thecatapi.com/images/nJsljkalm.jpg', 944, 1024, 'bsho', 'British Shorthair', 'Affectionate, Easy Going, Gentle, Loyal, Patient, calm', 'United Kingdom'),
        ('Mdr6QqID0', 'https://cdn2.thecatapi.com/images/Mdr6QqID0.jpg', 1920, 1279, 'bure', 'Burmese', 'Curious, Intelligent, Gentle, Social, Interactive, Playful, Lively', 'Burma'),
        ('r530zDuJU', 'https://cdn2.thecatapi.com/images/r530zDuJU.jpg', 3504, 2336, 'buri', 'Burmilla', 'Easy Going, Friendly, Intelligent, Lively, Playful, Social', 'United Kingdom'),
        ('yqcbOxkWK', 'https://cdn2.thecatapi.com/images/yqcbOxkWK.jpg', 970, 500, 'crex', 'Cornish Rex', 'Affectionate, Intelligent, Active, Curious, Playful', 'United Kingdom'),
        ('lF3ZTucYp', 'https://cdn2.thecatapi.com/images/lF3ZTucYp.jpg', 1280, 720, 'cymr', 'Cymric', 'Gentle, Loyal, Intelligent, Playful', 'Canada'),
        ('4RzEwvyzz', 'https://cdn2.thecatapi.com/images/4RzEwvyzz.png', 1729, 1160, 'drex', 'Devon Rex', 'Highly interactive, Mischievous, Loyal, Social, Playful', 'United Kingdom'),
        ('yFwzO96ds', 'https://cdn2.thecatapi.com/images/yFwzO96ds.jpg', 1200, 776, 'drex', 'Devon Rex', 'Highly interactive, Mischievous, Loyal, Social, Playful', 'United Kingdom'),
        ('_BhPUA-L-', 'https://cdn2.thecatapi.com/images/_BhPUA-L-.jpg', 1000, 667, 'drex', 'Devon Rex', 'Highly interactive, Mischievous, Loyal, Social, Playful', 'United Kingdom'),
        ('DUxU01IY5', 'https://cdn2.thecatapi.com/images/DUxU01IY5.jpg', 1080, 1080, 'lihu', 'Dragon Li', 'Intelligent, Friendly, Gentle, Loving, Loyal', 'China'),
        ('AH61b9ziS', 'https://cdn2.thecatapi.com/images/AH61b9ziS.jpg', 2111, 1346, 'emau', 'Egyptian Mau', 'Agile, Dependent, Gentle, Intelligent, Lively, Loyal, Playful', 'Egypt'),
        ('2N4PhyqTG', 'https://cdn2.thecatapi.com/images/2N4PhyqTG.jpg', 800, 600, 'esho', 'Exotic Shorthair', 'Affectionate, Sweet, Loyal, Quiet, Peaceful', 'United States'),
        ('zJkeHza2K', 'https://cdn2.thecatapi.com/images/zJkeHza2K.jpg', 2048, 1511, 'esho', 'Exotic Shorthair', 'Affectionate, Sweet, Loyal, Quiet, Peaceful', 'United States'),
        ('Jxl7eRfCW', 'https://cdn2.thecatapi.com/images/Jxl7eRfCW.jpg', 1110, 730, 'esho', 'Exotic Shorthair', 'Affectionate, Sweet, Loyal, Quiet, Peaceful', 'United States'),
        ('KJF8fB_20', 'https://cdn2.thecatapi.com/images/KJF8fB_20.jpg', 820, 1024, 'esho', 'Exotic Shorthair', 'Affectionate, Sweet, Loyal, Quiet, Peaceful', 'United States'),
        ('njK25knLH', 'https://cdn2.thecatapi.com/images/njK25knLH.jpg', 1024, 823, 'hbro', 'Havana Brown', 'Affectionate, Curious, Demanding, Friendly, Intelligent, Playful', 'United Kingdom'),
        ('ZZmFRKWZZ', 'https://cdn2.thecatapi.com/images/ZZmFRKWZZ.jpg', 1980, 1355, 'acur', 'American Curl', 'Affectionate, Curious, Intelligent, Interactive, Lively, Playful, Social', 'United States'),
        ('5i_-8rPKS', 'https://cdn2.thecatapi.com/images/5i_-8rPKS.jpg', 1280, 818, 'chau', 'Chausie', 'Affectionate, Intelligent, Playful, Social', 'Egypt'),
        ('snxE5_PPX', 'https://cdn2.thecatapi.com/images/snxE5_PPX.jpg', 3888, 2592, 'chau', 'Chausie', 'Affectionate, Intelligent, Playful, Social', 'Egypt'),
        ('L-aDi29wP', 'https://cdn2.thecatapi.com/images/L-aDi29wP.jpg', 3264, 2448, 'chee', 'Cheetoh', 'Affectionate, Gentle, Intelligent, Social', 'United States'),
        ('mNOdlAkXR', 'https://cdn2.thecatapi.com/images/mNOdlAkXR.jpg', 1280, 800, 'chee', 'Cheetoh', 'Affectionate, Gentle, Intelligent, Social', 'United States'),
        ('oSpqGyUDS', 'https://cdn2.thecatapi.com/images/oSpqGyUDS.jpg', 1363, 1600, 'csho', 'Colorpoint Shorthair', 'Affectionate, Intelligent, Playful, Social', 'United States'),
        ('QCcTOaIQW', 'https://cdn2.thecatapi.com/images/QCcTOaIQW.jpg', 1553, 2047, 'jbob', 'Japanese Bobtail', 'Active, Agile, Clever, Easy Going, Intelligent, Lively, Loyal, Playful, Social', 'Japan'),
        ('RfdGhgEf3', 'https://cdn2.thecatapi.com/images/RfdGhgEf3.jpg', 1920, 1440, 'jbob', 'Japanese Bobtail', 'Active, Agile, Clever, Easy Going, Intelligent, Lively, Loyal, Playful, Social', 'Japan'),
        ('PgUVo_1n4', 'https://cdn2.thecatapi.com/images/PgUVo_1n4.jpg', 1200, 900, 'java', 'Javanese', 'Active, Devoted, Intelligent, Playful', 'United States'),
        ('V00qLe4Gw', 'https://cdn2.thecatapi.com/images/V00qLe4Gw.jpg', 1920, 1280, 'java', 'Javanese', 'Active, Devoted, Intelligent, Playful', 'United States'),
        ('O1X8xKt_H', 'https://cdn2.thecatapi.com/images/O1X8xKt_H.jpg', 1800, 2700, 'java', 'Javanese', 'Active, Devoted, Intelligent, Playful', 'United States'),
        ('xPuWATvp9', 'https://cdn2.thecatapi.com/images/xPuWATvp9.jpg', 1080, 1350, 'kora', 'Korat', 'Active, Loyal, highly intelligent, Expressive, Trainable', 'Thailand'),
        ('MxaS9brW9', 'https://cdn2.thecatapi.com/images/MxaS9brW9.jpg', 1200, 1799, 'lape', 'LaPerm', 'Affectionate, Friendly, Gentle, Intelligent, Playful, Quiet', 'Thailand'),
        ('gU5wUcOuo', 'https://cdn2.thecatapi.com/images/gU5wUcOuo.jpg', 1200, 800, 'manx', 'Manx', 'Easy Going, Intelligent, Loyal, Playful, Social', 'Isle of Man'),
        ('yFqH0s2H_', 'https://cdn2.thecatapi.com/images/yFqH0s2H_.jpg', 960, 960, 'munc', 'Munchkin', 'Agile, Easy Going, Intelligent, Playful', 'United States'),
        ('uk0SrrBbQ', 'https://cdn2.thecatapi.com/images/uk0SrrBbQ.jpg', 2329, 2097, 'munc', 'Munchkin', 'Agile, Easy Going, Intelligent, Playful', 'United States'),
        ('D2J3R7sUq', 'https://cdn2.thecatapi.com/images/D2J3R7sUq.jpg', 1024, 768, 'munc', 'Munchkin', 'Agile, Easy Going, Intelligent, Playful', 'United States'),
        ('wMndw0twO', 'https://cdn2.thecatapi.com/images/wMndw0twO.jpg', 1200, 1200, 'munc', 'Munchkin', 'Agile, Easy Going, Intelligent, Playful', 'United States'),
        ('mpcBi2Utm', 'https://cdn2.thecatapi.com/images/mpcBi2Utm.jpg', 1108, 734, 'munc', 'Munchkin', 'Agile, Easy Going, Intelligent, Playful', 'United States'),
        ('7afi4uNFM', 'https://cdn2.thecatapi.com/images/7afi4uNFM.jpg', 576, 570, 'norw', 'Norwegian Forest Cat', 'Sweet, Active, Intelligent, Social, Playful, Lively, Curious', 'Norway'),
        ('wJyw82pIl', 'https://cdn2.thecatapi.com/images/wJyw82pIl.jpg', 3840, 2160, 'norw', 'Norwegian Forest Cat', 'Sweet, Active, Intelligent, Social, Playful, Lively, Curious', 'Norway'),
        ('Pqcy8pOZG', 'https://cdn2.thecatapi.com/images/Pqcy8pOZG.jpg', 1000, 890, 'norw', 'Norwegian Forest Cat', 'Sweet, Active, Intelligent, Social, Playful, Lively, Curious', 'Norway'),
        ('aJAsEA8uU', 'https://cdn2.thecatapi.com/images/aJAsEA8uU.jpg', 1280, 853, 'ocic', 'Ocicat', 'Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social', 'United States'),
        ('imz2EwFWv', 'https://cdn2.thecatapi.com/images/imz2EwFWv.jpg', 1280, 850, 'ocic', 'Ocicat', 'Active, Agile, Curious, Demanding, Friendly, Gentle, Lively, Playful, Social', 'United States'),
        ('UYp1-LQxI', 'https://cdn2.thecatapi.com/images/UYp1-LQxI.jpg', 768, 1024, 'orie', 'Oriental', 'Energetic, Affectionate, Intelligent, Social, Playful, Curious', 'United States'),
        ('0Z9FWHLuK', 'https://cdn2.thecatapi.com/images/0Z9FWHLuK.jpg', 1100, 733, 'orie', 'Oriental', 'Energetic, Affectionate, Intelligent, Social, Playful, Curious', 'United States'),
        ('RhBsBQg6y', 'https://cdn2.thecatapi.com/images/RhBsBQg6y.jpg', 1200, 800, 'pers', 'Persian', 'Affectionate, loyal, Sedate, Quiet', 'Iran (Persia)'),
        ('AYfFc4vOB', 'https://cdn2.thecatapi.com/images/AYfFc4vOB.jpg', 1280, 859, 'pers', 'Persian', 'Affectionate, loyal, Sedate, Quiet', 'Iran (Persia)'),
        ('Pqtwt4FCq', 'https://cdn2.thecatapi.com/images/Pqtwt4FCq.jpg', 3864, 2577, 'pers', 'Persian', 'Affectionate, loyal, Sedate, Quiet', 'Iran (Persia)'),
        ('3Pem6K30P', 'https://cdn2.thecatapi.com/images/3Pem6K30P.jpg', 1250, 1387, 'pers', 'Persian', 'Affectionate, loyal, Sedate, Quiet', 'Iran (Persia)'),
        ('n6iJQcVtD', 'https://cdn2.thecatapi.com/images/n6iJQcVtD.jpg', 1920, 1353, 'pixi', 'Pixie-bob', 'Affectionate, Social, Intelligent, Loyal', 'United States'),
        ('wwFp9IiRd', 'https://cdn2.thecatapi.com/images/wwFp9IiRd.jpg', 1214, 826, 'raga', 'Ragamuffin', 'Affectionate, Friendly, Gentle, Calm', 'United States'),
        ('jI2dXfp26', 'https://cdn2.thecatapi.com/images/jI2dXfp26.png', 1259, 630, 'raga', 'Ragamuffin', 'Affectionate, Friendly, Gentle, Calm', 'United States'),
        ('83htMb1AJ', 'https://cdn2.thecatapi.com/images/83htMb1AJ.jpg', 3000, 2000, 'ragd', 'Ragdoll', 'Affectionate, Friendly, Gentle, Quiet, Easygoing', 'United States'),
        ('UYLI_E-SZ', 'https://cdn2.thecatapi.com/images/UYLI_E-SZ.jpg', 750, 500, 'ragd', 'Ragdoll', 'Affectionate, Friendly, Gentle, Quiet, Easygoing', 'United States'),
        ('qBqs3R_w4', 'https://cdn2.thecatapi.com/images/qBqs3R_w4.jpg', 1600, 1200, 'ragd', 'Ragdoll', 'Affectionate, Friendly, Gentle, Quiet, Easygoing', 'United States'),
        ('LIoOlcalr', 'https://cdn2.thecatapi.com/images/LIoOlcalr.jpg', 970, 908, 'rblu', 'Russian Blue', 'Active, Dependent, Easy Going, Gentle, Intelligent, Loyal, Playful, Quiet', 'Russia'),
        ('bpZGfNLW1', 'https://cdn2.thecatapi.com/images/bpZGfNLW1.png', 1100, 739, 'rblu', 'Russian Blue', 'Active, Dependent, Easy Going, Gentle, Intelligent, Loyal, Playful, Quiet', 'Russia'),
        ('q7izjTTa4', 'https://cdn2.thecatapi.com/images/q7izjTTa4.jpg', 960, 960, 'sfol', 'Scottish Fold', 'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving', 'United Kingdom'),
        ('JQMGbOP3q', 'https://cdn2.thecatapi.com/images/JQMGbOP3q.jpg', 1365, 2048, 'sfol', 'Scottish Fold', 'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving', 'United Kingdom'),
        ('G-zFLupdX', 'https://cdn2.thecatapi.com/images/G-zFLupdX.jpg', 2448, 1836, 'sfol', 'Scottish Fold', 'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving', 'United Kingdom'),
        ('btNeFAWNP', 'https://cdn2.thecatapi.com/images/btNeFAWNP.jpg', 1280, 851, 'sfol', 'Scottish Fold', 'Affectionate, Intelligent, Loyal, Playful, Social, Sweet, Loving', 'United Kingdom'),
        ('DFHMMPNcD', 'https://cdn2.thecatapi.com/images/DFHMMPNcD.jpg', 1080, 1319, 'siam', 'Siamese', 'Active, Agile, Clever, Sociable, Loving, Energetic', 'Thailand'),
        ('cs8MHOb5I', 'https://cdn2.thecatapi.com/images/cs8MHOb5I.jpg', 1080, 698, 'sibe', 'Siberian', 'Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate', 'Russia'),
        ('S1CN1w6Bt', 'https://cdn2.thecatapi.com/images/S1CN1w6Bt.jpg', 1741, 2327, 'snow', 'Snowshoe', 'Affectionate, Social, Intelligent, Sweet-tempered', 'United States'),
        ('v63sbirkC', 'https://cdn2.thecatapi.com/images/v63sbirkC.jpg', 736, 1108, 'soma', 'Somali', 'Mischievous, Tenacious, Intelligent, Affectionate, Gentle, Interactive, Loyal', 'Somalia'),
        ('o0eqzDky9', 'https://cdn2.thecatapi.com/images/o0eqzDky9.jpg', 768, 1024, 'tonk', 'Tonkinese', 'Curious, Intelligent, Social, Lively, Outgoing, Playful, Affectionate', 'Canada'),
        ('8cXEkQQwc', 'https://cdn2.thecatapi.com/images/8cXEkQQwc.jpg', 1600, 1200, 'char', 'Chartreux', 'Affectionate, Loyal, Intelligent, Social, Lively, Playful', 'France'),
        ('oLtx9gsxx', 'https://cdn2.thecatapi.com/images/oLtx9gsxx.jpg', 4027, 2680, 'ebur', 'European Burmese', 'Sweet, Affectionate, Loyal', 'Burma'),
        ('luT74s8zp', 'https://cdn2.thecatapi.com/images/luT74s8zp.jpg', 1080, 1080, 'mcoo', 'Maine Coon', 'Adaptable, Intelligent, Loving, Gentle, Independent', 'United States'),
        ('tHKLZkKZG', 'https://cdn2.thecatapi.com/images/tHKLZkKZG.jpg', 3504, 2336, 'rblu', 'Russian Blue', 'Active, Dependent, Easy Going, Gentle, Intelligent, Loyal, Playful, Quiet', 'Russia'),
        ('nhwAjEuEG', 'https://cdn2.thecatapi.com/images/nhwAjEuEG.jpg', 1080, 1080, 'srex', 'Selkirk Rex', 'Active, Affectionate, Dependent, Gentle, Patient, Playful, Quiet, Social', 'United States'),
        ('xfkK4cQvp', 'https://cdn2.thecatapi.com/images/xfkK4cQvp.jpg', 750, 904, 'srex', 'Selkirk Rex', 'Active, Affectionate, Dependent, Gentle, Patient, Playful, Quiet, Social', 'United States'),
        ('uTG1YFzJV', 'https://cdn2.thecatapi.com/images/uTG1YFzJV.jpg', 1080, 809, 'siam', 'Siamese', 'Active, Agile, Clever, Sociable, Loving, Energetic', 'Thailand'),
        ('84-HSUBbt', 'https://cdn2.thecatapi.com/images/84-HSUBbt.jpg', 1200, 800, 'siam', 'Siamese', 'Active, Agile, Clever, Sociable, Loving, Energetic', 'Thailand'),
        ('gZiG70w_u', 'https://cdn2.thecatapi.com/images/gZiG70w_u.jpg', 750, 937, 'sibe', 'Siberian', 'Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate', 'Russia'),
        ('XIK3w04V9', 'https://cdn2.thecatapi.com/images/XIK3w04V9.jpg', 1080, 1350, 'sibe', 'Siberian', 'Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate', 'Russia'),
        ('e4K-lKOic', 'https://cdn2.thecatapi.com/images/e4K-lKOic.jpg', 1920, 1200, 'sibe', 'Siberian', 'Curious, Intelligent, Loyal, Sweet, Agile, Playful, Affectionate', 'Russia'),
        ('4d4V586nt', 'https://cdn2.thecatapi.com/images/4d4V586nt.jpg', 750, 750, 'snow', 'Snowshoe', 'Affectionate, Social, Intelligent, Sweet-tempered', 'United States'),
        ('0lKfGvesZ', 'https://cdn2.thecatapi.com/images/0lKfGvesZ.jpg', 2048, 1360, 'soma', 'Somali', 'Mischievous, Tenacious, Intelligent, Affectionate, Gentle, Interactive, Loyal', 'Somalia'),
        ('5qNv0jHXW', 'https://cdn2.thecatapi.com/images/5qNv0jHXW.jpg', 1024, 1024, 'tonk', 'Tonkinese', 'Curious, Intelligent, Social, Lively, Outgoing, Playful, Affectionate', 'Canada'),
        ('8rTgmNHn6', 'https://cdn2.thecatapi.com/images/8rTgmNHn6.jpg', 750, 887, 'toyg', 'Toyger', 'Playful, Social, Intelligent', 'United States'),
        ('sWfuXbpSS', 'https://cdn2.thecatapi.com/images/sWfuXbpSS.jpg', 1446, 1168, 'toyg', 'Toyger', 'Playful, Social, Intelligent', 'United States'),
        ('DYOqsRy9f', 'https://cdn2.thecatapi.com/images/DYOqsRy9f.jpg', 1080, 720, 'tang', 'Turkish Angora', 'Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social', 'Turkey'),
        ('cSzaNCgq2', 'https://cdn2.thecatapi.com/images/cSzaNCgq2.jpg', 1024, 768, 'tang', 'Turkish Angora', 'Affectionate, Agile, Clever, Gentle, Intelligent, Playful, Social', 'Turkey'),
        ('Co5BH7YZT', 'https://cdn2.thecatapi.com/images/Co5BH7YZT.jpg', 1024, 768, 'tvan', 'Turkish Van', 'Agile, Intelligent, Loyal, Playful, Energetic', 'Turkey'),
        ('j9_ETlBMp', 'https://cdn2.thecatapi.com/images/j9_ETlBMp.jpg', 1090, 1600, 'tvan', 'Turkish Van', 'Agile, Intelligent, Loyal, Playful, Energetic', 'Turkey'),
        ('Ua8Kr2RuM', 'https://cdn2.thecatapi.com/images/Ua8Kr2RuM.jpg', 1080, 1350, 'tvan', 'Turkish Van', 'Agile, Intelligent, Loyal, Playful, Energetic', 'Turkey'),
        ('xIICfnlNm', 'https://cdn2.thecatapi.com/images/xIICfnlNm.jpg', 1696, 2544, 'ycho', 'York Chocolate', 'Playful, Social, Intelligent, Curious, Friendly', 'United States');